server:
  port: ${SERVICE_PORT:8181}

spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${SERVICE_DB_HOST:localhost}:${SERVICE_DB_PORT:5432}/${SERVICE_DB_DATABASE}
    username: ${SERVICE_DB_USER:postgres}
    password: ${SERVICE_DB_PASSWORD:postgres}
